import Head from "next/head";

import dynamic from "next/dynamic";

const FlowPanel = dynamic(
  () => import("../components").then((m) => m.FlowPanel),
  {
    ssr: false,
  }
);

export default function Home() {
  return (
    <>
      <Head>
        <title>demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: "100vh" }}>
        <button
          onClick={() => {
            console.log("###");
            document
              .getElementById("container")
              ?.dispatchEvent(new CustomEvent("add-edit-node"));
          }}
        >
          Add Edit Node
        </button>
        <div id="container"></div>
        <FlowPanel />
      </main>
    </>
  );
}
